- name: "Update os packages"
  become: true
  apt:
    update_cache: yes
    
- name: "Install NodeJs"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: populate /etc/environment
  become: true
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"
   
