- name: "Copy backend dist files"
  copy:
    src:  ~/project/backend/dist/
    dest: /home/ubuntu/udapeople/
    owner: ubuntu

- unarchive:
    src:  ~/project/backend/node_modules.tar.gz
    dest: /home/ubuntu/udapeople/

- name: "Change the working directory and start pm2 app service"
  shell: pm2 start main.js
  args:
    chdir: /home/ubuntu/udapeople/
